const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

exports.generateInvoicePDF = async (data) => {
    return new Promise((resolve, reject) => {
        try {
            // Create a new PDF document
            const doc = new PDFDocument({
                size: 'A4',
                margin: 50
            });

            // Collect PDF chunks
            const chunks = [];
            doc.on('data', chunk => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));

            // Add company logo
            if (data.logoPath) {
                const logoFilePath = path.join(__dirname, '../..', data.logoPath);
                if (fs.existsSync(logoFilePath)) {
                    doc.image(logoFilePath, 50, 50, { width: 150 });
                }
            } else {
                // Use default logo if available
                const defaultLogoPath = path.join(__dirname, '../../DefaultLogo/GCCompanyLogo.png');
                if (fs.existsSync(defaultLogoPath)) {
                    doc.image(defaultLogoPath, 50, 50, { width: 150 });
                }
            }

            // Add invoice header
            doc.fontSize(20)
               .text('INVOICE', 400, 50)
               .fontSize(10)
               .text(`Invoice No: ${data.invoiceNumber}`, 400, 80)
               .text(`Date: ${data.invoiceDate}`, 400, 95);

            // Company details
            doc.fontSize(12)
               .text('From:', 50, 150)
               .fontSize(10)
               .text(data.companyName, 50, 170)
               .text(data.companyAddress, 50, 185)
               .text(`GST: ${data.companyGST}`, 50, 215)
               .text(`Phone: ${data.companyPhone}`, 50, 230)
               .text(`Email: ${data.companyEmail}`, 50, 245);

            // Customer details
            doc.fontSize(12)
               .text('To:', 300, 150)
               .fontSize(10)
               .text(data.customerName, 300, 170)
               .text(data.customerAddress, 300, 185)
               .text(`GST: ${data.customerGST || 'N/A'}`, 300, 215);

            // Product table header
            let yPos = 300;
            doc.fontSize(10)
               .text('No.', 50, yPos)
               .text('Item', 100, yPos)
               .text('Qty', 250, yPos)
               .text('Rate', 300, yPos)
               .text('Amount', 350, yPos)
               .text('GST %', 400, yPos)
               .text('GST Amt', 450, yPos)
               .text('Total', 500, yPos);

            // Draw header line
            yPos += 15;
            doc.moveTo(50, yPos).lineTo(550, yPos).stroke();
            yPos += 10;

            // Product rows
            let totalAmount = 0;
            let totalGST = 0;

            data.products.forEach((product, index) => {
                doc.text(String(index + 1), 50, yPos)
                   .text(product.name, 100, yPos)
                   .text(String(product.qty), 250, yPos)
                   .text(product.rate.toFixed(2), 300, yPos)
                   .text(product.subtotal.toFixed(2), 350, yPos)
                   .text(product.gst + '%', 400, yPos)
                   .text(product.gstAmount.toFixed(2), 450, yPos)
                   .text(product.total.toFixed(2), 500, yPos);

                totalAmount += product.subtotal;
                totalGST += product.gstAmount;
                yPos += 20;
            });

            // Totals section
            yPos += 20;
            doc.fontSize(10)
               .text('Subtotal:', 400, yPos)
               .text(totalAmount.toFixed(2), 500, yPos);

            yPos += 20;
            doc.text('Total GST:', 400, yPos)
               .text(totalGST.toFixed(2), 500, yPos);

            yPos += 20;
            doc.fontSize(12)
               .text('Grand Total:', 400, yPos)
               .text((totalAmount + totalGST).toFixed(2), 500, yPos);

            // Footer with watermark
            doc.fontSize(8)
               .fillColor('gray')
               .text(
                   'Generated by Gahranox Carvel Labs Technologies Billing Software',
                   50,
                   doc.page.height - 50,
                   { align: 'center' }
               );

            // Add QR code if available
            const qrCodePath = path.join(__dirname, '../../DefaultLogo/GCCompanyQR.png');
            if (fs.existsSync(qrCodePath)) {
                doc.image(qrCodePath, 250, doc.page.height - 100, { width: 100 });
            }

            // Finalize the PDF
            doc.end();

        } catch (error) {
            reject(error);
        }
    });
};